### PR TITLE
Fix compilation on gentoo

### LINKED ISSUE #23: Cannot build on gentoo
Trying to build on gentoo, compilation is failing against mariadb or mysql.

`/var/tmp/portage/ctrl-tango/tango-db-5.15/work/TangoDatabase-Database-Release-5.14/DataBaseUtils.cpp:784:3: error: ‘my_bool’ was not declared in this scope; did you mean ‘bool’?
  784 |   my_bool my_auto_reconnect=1;`
`/var/tmp/portage/ctrl-tango/tango-db-5.15/work/TangoDatabase-Database-Release-5.14/DataBaseUtils.cpp:785:61: error: ‘my_auto_reconnect’ was not declared in this scope
  785 |   if (mysql_options(conn_pool[loop].db,MYSQL_OPT_RECONNECT,&my_auto_reconnect) !=0)`

mysql version 8.0.20
mariadb version 10.4.12

Upon checking this my_bool is defined in mysql.h but it is not defined for mysql.
As for mariadb this file can be found in 2 places : 
  - /usr/include/mysql/
  - /usr/include/mariadb/

But on configure/FindMysql.cmake, we only check on the first directory, and cannot build. Changing the path there fix the issue.

Mariadb installation on gentoo might not use default path, so we might not have this issue on other distributions with mariadb. But if my_bool is not defined in newer version of mysql, we might need to change the code not to use it anymore.

### PR DESCRIPTION
**Pull request by t-b**
Close #23. 

@dlacoste-esrf: Please test the fix on gentoo. Thanks.

### CODE REVIEW

**Comment by dlacoste-esrf** [comment]
thx, it's working good !

**Comment by t-b** [comment]
@mliszcz @bourtemb Please review. Thanks.

File: DataBase.h [hunk 1]
```diff
@@ -51,6 +51,11 @@
 #include <mysql.h>
 #include <update_starter.h>
 
+#ifndef LIBMARIADB
+#ifndef my_bool
+typedef bool my_bool;
+#endif
+#endif
```
Comment (mliszcz) [inline DataBase.h]: Have you tested this on older MySQL versions? Because (at least in 5.7) they do not have a macro for that, just a typedef:
https://github.com/mysql/mysql-server/blob/mysql-5.7.31/include/mysql.h#L49
And their typedef is pointing to `char`, which conflicts with what you added here (and this is a compilation error).

People on the Internet are checking the version, like here:
https://github.com/zussel/matador/commit/9869f4ede37be748102fa92fce55a84b016902f0#diff-c4fe758407c037ec2b8fe051215fb3cbR8-R10

Another option is to stop using my_bool in our code. There is just one single occurrence in DataBaseUtils.cpp. We just need to detect somehow what boolean type mysql is using, for instance with something like:
```diff
-               my_bool my_auto_reconnect=1;
+               decltype(mysql_thread_init()) my_auto_reconnect=1;
                if (mysql_options(conn_pool[loop].db,MYSQL_OPT_RECONNECT,&my_auto_reconnect) !=0)
```
If you want to keep it C++03 compatible for any reasons, this will be a bit more complicated (may require overloading, tag dispatching or SFINAE).

**Review by mliszcz — CHANGES_REQUESTED** [review]

File: DataBase.h (hunk 1 above)
Comment (t-b) [reply DataBase.h]: @mliszcz I only tested with debian buster. I'll do a test with debian wheezy.

Comment (mliszcz) [reply DataBase.h]: @t-b did you use packages from debian repos? I don't know what wheezy has but it looks like neither buster nor stretch provide MySQL. libmysqlclient-dev is alias for mariadb package: https://packages.debian.org/buster/default-libmysqlclient-dev
And if you check who provides `mysql.h`, there is only libmariadb-dev: https://packages.debian.org/search?searchon=contents&keywords=mysql.h&mode=path&suite=stable&arch=any

Comment (t-b) [reply DataBase.h]: @mliszcz Thanks for the review. Indeed this breaks with older mysql versions, as I just tested with debian wheezy. I've now revised the code and only define my_bool for newer MYSQL versions.

**Review by mliszcz — APPROVED** [review]
LGTM!
